project:
  name: cfn-ps-databricks-unified-data-analytics-platform
  owner: noreply@amazon.com
  package_lambda: true 
  shorten_stack_name: true 
  s3_regional_buckets: true 
  regions: 
    - us-east-1
  parameters:
    BucketName: db-$[taskcat_random-string]
    IAMRole: 'qstest-iam-$[taskcat_genpass_8A]'
    KeyAlias: ''
    KeyReuseForClusterVolumes: ''
    KeyUseCases: ''
    Username: sshvans@amazon.com
    AccountId: OVERRIDE
    HIPAAparm: 'No'
    Password: OVERRIDE
    PrivateLinkMode: Disabled
    QSS3BucketName: $[taskcat_autobucket]
    QSS3KeyPrefix: cfn-ps-databricks-unified-data-analytics-platform/
    TagValue: qstest
tests:
  default:
    template: templates/databricks-multi-workspace.template.yaml